"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { visualAssetPending } from "@/lib/ai/visual-prompt";
import { ImageIcon, Loader2, RefreshCcw, Sparkles } from "lucide-react";

interface AiaAsset {
  id: string;
  type: string;
  purpose?: string;
  status: string;
  generation?: string;
  asset_path?: string;
}

const POLL_MS = 6000;

export function AiVisuals({ project }: { project: { id: string; universal?: { visuals_plan?: AiaAsset[] } | null } }) {
  const router = useRouter();
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const assets = (project.universal?.visuals_plan ?? []).filter((v) => v.status !== "SKIPPED");
  const pending = assets.filter((v) => visualAssetPending(v)).length;

  // Background queue renders PLANNED assets server-side; poll until settled.
  useEffect(() => {
    if (pending === 0 || busy) {
      if (pollRef.current) {
        clearInterval(pollRef.current);
        pollRef.current = null;
      }
      return;
    }
    if (!pollRef.current) {
      pollRef.current = setInterval(() => router.refresh(), POLL_MS);
    }
    return () => {
      if (pollRef.current) {
        clearInterval(pollRef.current);
        pollRef.current = null;
      }
    };
  }, [pending, busy, router]);

  if (!assets.length) return null;

  async function generate(assetId: string, force = false) {
    setBusy(assetId);
    setError(null);
    try {
      const res = await fetch(`/api/tech-pack/${project.id}/visuals`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ assetId, force }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? "Generation failed.");
      } else {
        router.refresh();
      }
    } catch {
      setError("Could not reach the generation endpoint.");
    } finally {
      setBusy(null);
    }
  }

  return (
    <section className="rounded-[24px] border border-ink/10 bg-sheet p-5 shadow-sheet">
      <div className="mb-3 flex flex-wrap items-baseline justify-between gap-2">
        <div className="flex items-baseline gap-3">
          <span className="rounded-full bg-[#bbb9f9] px-2.5 py-0.5 font-mono text-[10px] uppercase tracking-[0.2em] text-[#5f50bc]">
            02.6 / AI renders
          </span>
          <h3 className="font-heading text-lg font-semibold">AI product visuals</h3>
        </div>
        <span className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink-soft">
          Gemini image model · reference image as ground truth
          {pending > 0 ? " · rendering…" : ""}
        </span>
      </div>
      <p className="mb-4 max-w-3xl text-sm text-ink-soft">
        Every visual is generated by AI from your reference photo and the structured pack data — silhouette,
        materials, colours and measurements stay exactly as specified. Nothing is drawn procedurally.
      </p>

      {error ? (
        <div className="mb-4 rounded-2xl border border-red-600/30 bg-red-600/10 p-3 text-xs text-red-700">{error}</div>
      ) : null}

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {assets.map((v) => {
          const isBusy = busy === v.id;
          const generated = Boolean(v.asset_path);
          const stale = v.status === "GENERATED" && !generated;
          const queued = isBusy || v.status === "PLANNED" || stale;
          return (
            <div
              key={v.id}
              className="group overflow-hidden rounded-[24px] border border-ink/10 bg-paper/60 transition-colors duration-300 hover:border-signal/40"
            >
              <div className="relative">
                {v.asset_path ? (
                  <img
                    src={v.asset_path}
                    alt={`${v.type.replace(/_/g, " ")} AI render`}
                    className="aspect-square w-full bg-white object-contain"
                  />
                ) : (
                  <div className="flex aspect-square w-full flex-col items-center justify-center gap-2 bg-white">
                    {queued ? (
                      <>
                        <Loader2 className="size-6 animate-spin text-signal" />
                        <span className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink-soft">
                          {isBusy ? "Rendering…" : "Queued"}
                        </span>
                      </>
                    ) : v.status === "FAILED" ? (
                      <>
                        <ImageIcon className="size-6 text-red-400" />
                        <span className="font-mono text-[9px] uppercase tracking-[0.18em] text-red-600">
                          Render failed
                        </span>
                      </>
                    ) : (
                      <ImageIcon className="size-6 text-ink/25" />
                    )}
                  </div>
                )}
                {generated ? (
                  <span className="absolute left-3 top-3 rounded-full border border-white/40 bg-ink/70 px-2 py-0.5 font-mono text-[8px] uppercase tracking-[0.2em] text-white backdrop-blur-sm">
                    AI render
                  </span>
                ) : null}
              </div>
              <div className="border-t border-ink/10 p-3">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-[10px] font-semibold uppercase tracking-[0.1em]">
                    {v.type.replace(/_/g, " ")}
                  </span>
                  <span
                    className={`font-mono text-[9px] uppercase ${
                      v.status === "GENERATED" && generated
                        ? "text-[#0c9358]"
                        : v.status === "FAILED"
                          ? "text-red-600"
                          : "text-signal"
                    }`}
                  >
                    {v.status === "GENERATED" && !generated ? "queued" : v.status === "PLANNED" ? "queued" : v.status}
                  </span>
                </div>
                {v.purpose ? <p className="mt-1 text-xs text-ink-soft">{v.purpose}</p> : null}
                <Button
                  size="sm"
                  variant={generated ? "outline" : "default"}
                  className="mt-3 w-full rounded-full"
                  disabled={isBusy}
                  onClick={() => generate(v.id, generated)}
                >
                  {isBusy ? (
                    <Loader2 className="size-3.5 animate-spin" />
                  ) : generated ? (
                    <RefreshCcw className="size-3.5" />
                  ) : v.status === "FAILED" ? (
                    <RefreshCcw className="size-3.5" />
                  ) : (
                    <Sparkles className="size-3.5" />
                  )}
                  {generated
                    ? "Regenerate"
                    : v.status === "FAILED"
                      ? "Retry render"
                      : stale
                        ? "Render queued asset"
                        : "Render with AI"}
                </Button>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
