import type { TechPack } from "@/lib/schemas/tech-pack";

/**
 * AI visual asset prompt engineering for the technical pack.
 *
 * IMPORTANT:
 * These assets are intentionally generated by an AI image model.
 *
 * The prompts are designed to make the model behave like a technical
 * documentation renderer rather than a creative image generator.
 *
 * SOURCE OF TRUTH:
 *
 *   Reference image
 *      → visual appearance / observable geometry / colour / construction
 *
 *   Structured TechPack data
 *      → dimensions / POM / tolerances / materials / variants /
 *        construction / labels / compliance / exact text
 *
 * The AI must never invent missing information.
 */

export const VISUAL_ASSET_IDS = [
  "va-hero",
  "va-front",
  "va-back",
  "va-construction",
  "va-pom",
  "va-sizechart",
  "va-care",
  "va-materials",
] as const;

export type VisualAssetId = (typeof VISUAL_ASSET_IDS)[number];

export interface VisualAssetStatusLike {
  id: string;
  type?: string;
  status: string;
  asset_path?: string | null;
}

/**
 * True when the asset still needs a render.
 *
 * GENERATED without an asset path is treated as pending for backwards
 * compatibility with packs created before the AI-render queue existed.
 */
export function visualAssetPending(v: VisualAssetStatusLike): boolean {
  if (v.status === "GENERATED") return !v.asset_path;

  return v.status === "PLANNED" || v.status === "FAILED";
}

export interface VisualPromptContext {
  pack: TechPack;
  sizes: string[];
}

/* -------------------------------------------------------------------------- */
/* GLOBAL VISUAL SYSTEM                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Shared instruction injected into every visual asset.
 *
 * This is intentionally verbose. Repetition is useful here because every
 * image-generation request is independent and the model must receive the
 * full technical-documentation contract every time.
 */
const GLOBAL_VISUAL_SYSTEM = `
# TECHNICAL DOCUMENTATION MODE

You are generating a professional manufacturing-grade technical documentation
asset for a physical product.

You are NOT generating concept art.
You are NOT redesigning the product.
You are NOT creating a generic example.
You are NOT creating marketing artwork.
You are NOT allowed to improve, beautify, simplify, modernize, stylize,
or reinterpret the product.

The supplied product reference and structured technical-pack data describe
ONE REAL PRODUCT.

Your job is to faithfully document that exact product.

---

# SOURCE-OF-TRUTH HIERARCHY

There are two authoritative sources.

SOURCE A — REFERENCE IMAGE
Controls observable visual information:

- overall appearance
- silhouette
- proportions
- visible geometry
- visible components
- visible construction
- visible seams
- visible hardware
- visible trims
- visible surface treatment
- visible colour
- visible material appearance

SOURCE B — STRUCTURED PACK DATA
Controls factual specification information:

- product name
- product category
- product type
- colourway codes
- measurements
- POMs
- tolerances
- material specifications
- composition
- GSM
- construction steps
- labels
- care information
- variants
- grading values
- compliance information

When a numerical or specification value exists in structured data,
use the structured data.

When a visual characteristic is visible in the reference image,
preserve the reference.

If information is missing from BOTH sources:

DO NOT INVENT IT.

Omission is preferable to fabrication.

---

# UNIVERSAL PRODUCT SUPPORT

The product may be ANY physical product, including:

- apparel
- footwear
- bags
- accessories
- furniture
- packaging
- electronics
- consumer products
- industrial products
- tools
- equipment
- components
- lifestyle products
- manufactured goods

Do not assume apparel terminology unless the product data indicates apparel.

Automatically adapt technical terminology to the actual product category.

---

# PRODUCT IDENTITY LOCK

Every generated asset belongs to the SAME product.

Across all assets preserve:

- exact silhouette
- exact proportions
- exact component relationships
- exact visible geometry
- exact material placement
- exact colour placement
- exact construction logic
- exact component count
- exact variant logic

Never redesign the product between assets.

Never create a different interpretation for the back view.

Never introduce a component because it is typical for the product category.

Never remove a component simply because it is difficult to render.

Never make the product more symmetrical than the source.

Never "correct" unusual geometry.

---

# PRECISION RULE

TECHNICAL ACCURACY HAS HIGHER PRIORITY THAN VISUAL COMPLETENESS.

If you cannot confidently determine a detail:

OMIT IT.

Do not:

- guess
- estimate
- interpolate
- round
- normalize
- paraphrase
- fabricate
- infer typical construction
- invent measurements
- invent materials
- invent labels
- invent certifications
- invent supplier information
- invent component IDs

---

# TECHNICAL DOCUMENT VISUAL LANGUAGE

Use:

- precision technical illustration
- professional industrial documentation
- clean technical linework
- controlled line hierarchy
- orthographic projection where requested
- precise alignment
- disciplined spacing
- generous whitespace
- neutral documentation background
- restrained technical typography
- clear annotation hierarchy
- production-oriented composition

Avoid:

- cartoon aesthetics
- concept-art aesthetics
- exaggerated perspective
- decorative gradients
- unnecessary glow
- cinematic colour grading
- fantasy materials
- decorative backgrounds
- lifestyle scenes
- unnecessary 3D effects
- ornamental frames

---

# LINE HIERARCHY

Primary silhouette:
2.0–2.5 px visual weight

Secondary construction:
1.2–1.5 px

Internal technical detail:
0.8–1.0 px

Dimension lines:
0.8–1.0 px

Extension lines:
0.8–1.0 px

Centerlines:
0.6–0.8 px dashed

Hidden lines:
0.6–0.8 px dashed

Callout leaders:
0.8–1.0 px

---

# TYPOGRAPHY

Technical typography must be:

- highly legible
- clean
- restrained
- uppercase where specified
- compact
- engineering/documentation oriented

Do not use decorative fonts.

Do not distort characters.

Do not fabricate text.

Do not paraphrase structured-data text when exact wording is required.

Do not add explanatory copy that does not exist in the data.

---

# TEXT ACCURACY

Any text supplied by structured data must be reproduced exactly
when the asset requires that field.

Preserve:

- spelling
- numbers
- decimals
- units
- punctuation
- identifiers
- capitalization where specified

A wrong technical value is a critical defect.

If exact text cannot be rendered reliably:

prefer omitting the field rather than inventing or corrupting it.

---

# NUMERICAL ACCURACY

Every numerical value displayed inside the image must come from
the structured data or be mathematically derived from explicitly supplied
values where the asset specifically requires a calculation.

Never:

- estimate
- visually measure
- round
- approximate
- invent
- interpolate missing values

When displaying a value, preserve its exact representation from the data
whenever possible.

---

# CROSS-ASSET CONSISTENCY

The following assets form ONE DOCUMENT:

1. HERO
2. FRONT FLAT
3. BACK FLAT
4. CONSTRUCTION GUIDE
5. POM DIAGRAM
6. SIZE GRADING
7. CARE LABEL
8. MATERIAL BOARD

The same product must appear consistent throughout.

The front flat is the master technical silhouette.

The back flat must represent the same product.

The POM diagram must use the same product geometry as the technical flat.

The grading asset must use the same geometry and measurement system.

The construction guide must reference the same components.

The material board must reference the same materials.

---

# OUTPUT DISCIPLINE

Generate ONLY the requested asset.

Do not add:

- extra views
- extra charts
- extra pages
- decorative title pages
- additional components
- unrelated measurements
- fictional annotations

No watermark.

No generated logo unless explicitly present in the supplied data/reference.

No decorative border around the artwork unless explicitly requested.

The result must look like a professional technical-pack asset prepared
for a factory, supplier, technical designer, engineer, or QC team.
`.trim();

/* -------------------------------------------------------------------------- */
/* DATA GROUNDING                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Safely converts unknown values into displayable strings without changing
 * their meaning.
 */
function displayValue(value: unknown): string {
  if (value === null || value === undefined) return "—";

  if (typeof value === "string") return value;

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

/**
 * Build a flat, deterministic representation of the real TechPack data.
 *
 * IMPORTANT:
 * Do not aggressively slice arrays here.
 *
 * The image model needs the complete specification available to it.
 * Prompt length should be managed by the caller/model infrastructure,
 * not by silently deleting manufacturing information.
 */
export function summarizePackData(
  pack: TechPack,
  sizes: string[],
): string {
  const lines: string[] = [];

  /* ---------------------------------------------------------------------- */
  /* PRODUCT                                                                */
  /* ---------------------------------------------------------------------- */

  lines.push("# PRODUCT");

  lines.push(`PRODUCT NAME: ${displayValue(pack.product.name)}`);

  if (pack.product.category) {
    lines.push(`CATEGORY: ${displayValue(pack.product.category)}`);
  }

  if (pack.product.product_type) {
    lines.push(`PRODUCT TYPE: ${displayValue(pack.product.product_type)}`);
  }

  /* ---------------------------------------------------------------------- */
  /* COLOURWAYS                                                             */
  /* ---------------------------------------------------------------------- */

  if (pack.colorways.length) {
    lines.push("");
    lines.push("# COLORWAYS");

    for (const colorway of pack.colorways) {
      const faces = [
        colorway.face_a,
        colorway.face_b,
      ]
        .filter(Boolean)
        .join(" / ");

      const parts = [
        `NAME=${displayValue(colorway.name)}`,
        `CODE=${displayValue(colorway.code)}`,
      ];

      if (colorway.pantone) {
        parts.push(`PANTONE=${displayValue(colorway.pantone)}`);
      }

      if (faces) {
        parts.push(`FACES=${faces}`);
      }

      lines.push(`- ${parts.join(" | ")}`);
    }
  }

  /* ---------------------------------------------------------------------- */
  /* SIZES                                                                  */
  /* ---------------------------------------------------------------------- */

  if (sizes.length) {
    lines.push("");
    lines.push("# DEFINED SIZES / VARIANTS");

    sizes.forEach((size, index) => {
      lines.push(`${index + 1}. ${size}`);
    });
  }

  /* ---------------------------------------------------------------------- */
  /* MEASUREMENTS / POM                                                     */
  /* ---------------------------------------------------------------------- */

  if (pack.measurements.length) {
    lines.push("");
    lines.push("# MEASUREMENTS / POM");

    lines.push(
      "Each measurement below is factual structured data. " +
      "Do not invent or estimate values.",
    );

    for (const measurement of pack.measurements) {
      const values = sizes
        .filter((size) => measurement.values[size] !== undefined)
        .map(
          (size) =>
            `${size}=${displayValue(measurement.values[size])}`,
        )
        .join(", ");

      lines.push(
        [
          `ID=${displayValue(measurement.id)}`,
          `NAME=${displayValue(measurement.name)}`,
          `TOLERANCE=${displayValue(measurement.tolerance)}`,
          `VALUES=${values || "NO VALUE PROVIDED"}`,
        ].join(" | "),
      );
    }
  }

  /* ---------------------------------------------------------------------- */
  /* MATERIALS                                                              */
  /* ---------------------------------------------------------------------- */

  if (pack.materials.length) {
    lines.push("");
    lines.push("# MATERIALS");

    for (const material of pack.materials) {
      const composition =
        typeof material.composition?.value === "string"
          ? material.composition.value
          : undefined;

      const parts = [
        `NAME=${displayValue(material.name)}`,
        `TYPE=${displayValue(material.type)}`,
      ];

      if (composition) {
        parts.push(`COMPOSITION=${composition}`);
      }

      if (material.gsm?.value !== undefined) {
        parts.push(`GSM=${displayValue(material.gsm.value)}`);
      }

      if (material.color) {
        parts.push(`COLOR=${displayValue(material.color)}`);
      }

      lines.push(`- ${parts.join(" | ")}`);
    }
  }

  /* ---------------------------------------------------------------------- */
  /* CONSTRUCTION                                                           */
  /* ---------------------------------------------------------------------- */

  if (pack.construction.length) {
    lines.push("");
    lines.push("# CONSTRUCTION / ASSEMBLY");

    let globalStep = 1;

    for (const section of pack.construction) {
      for (const item of section.items) {
        lines.push(
          `${globalStep}. ${displayValue(item)}`,
        );

        globalStep += 1;
      }
    }
  }

  /* ---------------------------------------------------------------------- */
  /* LABELS                                                                 */
  /* ---------------------------------------------------------------------- */

  if (pack.labels.length) {
    lines.push("");
    lines.push("# LABELS");

    for (const label of pack.labels) {
      const parts = [
        `NAME=${displayValue(label.name)}`,
      ];

      if (label.placement) {
        parts.push(`PLACEMENT=${displayValue(label.placement)}`);
      }

      if (label.content) {
        parts.push(`CONTENT=${displayValue(label.content)}`);
      }

      lines.push(`- ${parts.join(" | ")}`);
    }
  }

  /* ---------------------------------------------------------------------- */
  /* CARE                                                                   */
  /* ---------------------------------------------------------------------- */

  const careLabels = pack.labels.filter((label) =>
    /care/i.test(label.name),
  );

  if (careLabels.length) {
    lines.push("");
    lines.push("# CARE / COMPLIANCE");

    for (const care of careLabels) {
      lines.push(
        `CARE LABEL: ${displayValue(care.name)}`,
      );

      if (care.content) {
        lines.push(
          `CARE CONTENT: ${displayValue(care.content)}`,
        );
      }

      if (care.placement) {
        lines.push(
          `CARE PLACEMENT: ${displayValue(care.placement)}`,
        );
      }
    }
  }

  return lines.join("\n");
}

/* -------------------------------------------------------------------------- */
/* ASSET DIRECTIVES                                                           */
/* -------------------------------------------------------------------------- */

interface AssetDirective {
  headline: string;
  body: string;
}

const DIRECTIVES: Record<VisualAssetId, AssetDirective> = {
  /* ---------------------------------------------------------------------- */
  /* HERO                                                                   */
  /* ---------------------------------------------------------------------- */

  "va-hero": {
    headline: "ASSET: HERO PRODUCT RENDER — PHOTOREALISTIC STUDIO STUDY",

    body: `
OBJECTIVE:

Create a premium photorealistic studio representation of the EXACT PRODUCT
shown in the supplied reference image.

This image exists to establish visual product identity.

REFERENCE FIDELITY:

Preserve exactly:

- silhouette
- proportions
- geometry
- visible components
- component placement
- visible seams
- stitching
- hardware
- trims
- labels
- openings
- closures
- material appearance
- surface finish
- colour

Do not redesign the product.

Do not make it more luxurious, fashionable, futuristic, minimal,
symmetrical, or commercially attractive than the reference.

CAMERA:

- neutral professional product-photography camera
- straight or minimally elevated perspective
- controlled perspective distortion
- no fisheye
- no extreme wide-angle lens
- complete product visible
- no crop

COMPOSITION:

- seamless light-grey or neutral studio background
- product occupies approximately 65–75% of the frame
- centered
- balanced negative space
- no props
- no hands
- no people
- no environment
- no mannequin unless explicitly required by the reference

LIGHTING:

- large soft top-front key light
- controlled neutral fill
- subtle contact shadow
- accurate material response
- no dramatic rim lighting
- no cinematic colour grading
- no glow

MATERIAL FIDELITY:

Preserve real physical characteristics:

- weave
- knit
- grain
- roughness
- gloss
- reflectivity
- transparency
- thickness
- finish

Do not change the material merely to make the render look more premium.

COLOUR:

Match the reference image and structured colourway data.

Do not shift colour through artistic grading.

OUTPUT:

Photorealistic, clean, high-end product photography suitable for the
hero section of a professional manufacturing technical pack.
`.trim(),
  },

  /* ---------------------------------------------------------------------- */
  /* FRONT                                                                  */
  /* ---------------------------------------------------------------------- */

  "va-front": {
    headline: "ASSET: PRECISION TECHNICAL FLAT — FRONT VIEW",

    body: `
OBJECTIVE:

Generate the exact FRONT ORTHOGRAPHIC TECHNICAL FLAT of the product.

This is a manufacturing reference drawing.

PROJECTION:

- true front view
- orthographic
- zero perspective
- zero lens distortion
- centered
- stable horizontal alignment
- stable vertical alignment

GEOMETRY:

Translate the product reference into precise technical linework.

Show all supported:

- outer silhouette
- component boundaries
- panels
- seams
- topstitching
- openings
- closures
- pockets
- hardware
- trims
- labels
- vents
- interfaces
- functional components

REFERENCE PRIORITY:

If a visible construction detail exists in the reference,
preserve it.

If a detail is not visible and is not defined in structured data,
omit it.

SYMMETRY:

If symmetrical, maintain accurate bilateral symmetry.

If asymmetrical, preserve the asymmetry.

Never automatically mirror uncertain geometry.

LINEWORK:

- stronger outer contour
- lighter internal construction
- precise intersections
- clean seam continuity
- no broken geometry

COLOUR:

Use restrained flat colour/fill only when it helps identify actual
colour/material regions.

Do not use photorealistic shading.

Do not use dramatic lighting.

Do not use gradients.

DO NOT INCLUDE:

- dimensions
- POM arrows
- measurement labels
- construction callouts
- size grading
- material board
- care symbols

TITLE:

FIG. 1 — FRONT FLAT SKETCH

SUBTITLE:

PRECISION TECHNICAL DRAWING
PROCEDURAL — FROM STRUCTURED DATA

This front view becomes the visual master reference for downstream
technical assets.
`.trim(),
  },

  /* ---------------------------------------------------------------------- */
  /* BACK                                                                   */
  /* ---------------------------------------------------------------------- */

  "va-back": {
    headline: "ASSET: PRECISION TECHNICAL FLAT — BACK VIEW",

    body: `
OBJECTIVE:

Generate the exact BACK ORTHOGRAPHIC TECHNICAL FLAT corresponding
to the same product represented in the front technical flat.

PROJECTION:

- true rear view
- orthographic
- zero perspective
- zero lens distortion
- same visual scale logic as the front view
- centered

SHOW:

- complete rear silhouette
- rear panels
- seams
- stitching
- openings
- closures
- pockets
- vents
- hardware
- labels
- trims
- reinforcement
- functional elements

REFERENCE RULE:

Only display details that are:

1. visible in the reference, OR
2. explicitly defined by structured data.

Never assume a conventional rear construction.

Never invent hidden components.

Never automatically mirror front details.

SYMMETRY:

Preserve actual symmetry and actual asymmetry.

DIMENSIONS:

Do not include dimensions.

Do not include POM labels.

Do not include measurement arrows.

Do not include construction callouts.

Do not include grading overlays.

TITLE:

FIG. 2 — BACK FLAT SKETCH

SUBTITLE:

PRECISION TECHNICAL DRAWING
PROCEDURAL — FROM STRUCTURED DATA

The back view must unmistakably describe the same physical product
as FIG. 1.
`.trim(),
  },

  /* ---------------------------------------------------------------------- */
  /* CONSTRUCTION                                                           */
  /* ---------------------------------------------------------------------- */

  "va-construction": {
    headline:
      "ASSET: CONSTRUCTION ASSEMBLY GUIDE — NUMBERED CALLOUTS",

    body: `
OBJECTIVE:

Create a professional manufacturing construction guide from the
supplied CONSTRUCTION data.

The purpose is to communicate HOW THE PRODUCT IS ASSEMBLED.

CONSTRUCTION DATA IS AUTHORITATIVE FOR:

- operation order
- operation names
- assembly sequence
- component relationships
- construction zones
- joining methods
- stitching
- fastening
- reinforcement
- finishing
- special instructions

NUMBERING:

Every supplied operation must receive exactly one numbered callout.

Use:

01
02
03
04
...
N

Preserve the exact supplied order.

Never:

- renumber
- merge steps
- split steps
- invent intermediate steps
- remove steps

CALLOUT STRUCTURE:

Each operation uses:

[NUMBERED CIRCLE]
        |
        |
        ↓
EXACT OPERATION ZONE

The leader line must terminate at the actual component,
seam, interface, fastening point, or construction region.

Do not place leaders approximately.

Do not point to empty space.

Do not allow excessive crossing.

EXPLODED VIEW:

Use an exploded view ONLY when the supplied data defines physically
separable components.

Otherwise use an assembled technical product view.

If exploded:

- preserve component orientation
- preserve assembly direction
- preserve component relationships
- do not invent internal parts

LEGEND:

Create a clean right-side legend.

Each row:

01  [EXACT OPERATION]
02  [EXACT OPERATION]
03  [EXACT OPERATION]

Where detailed descriptions are supplied, preserve their wording.

PRODUCT:

The illustrated product must remain geometrically consistent with
the front and back technical flats.

STYLE:

- clean technical illustration
- muted technical linework
- minimal flat colour
- no photorealistic environment
- no scenery
- no decorative effects

TITLE:

CONSTRUCTION GUIDE

SUBTITLE:

NUMBERED ASSEMBLY CALLOUTS
PROCEDURAL — FROM STRUCTURED DATA
`.trim(),
  },

  /* ---------------------------------------------------------------------- */
  /* POM                                                                    */
  /* ---------------------------------------------------------------------- */

  "va-pom": {
    headline:
      "ASSET: PRECISION POM — POINT OF MEASURE DIMENSION DIAGRAM",

    body: `
OBJECTIVE:

Create an engineering-grade POINT OF MEASURE diagram mapping every
supplied measurement to its exact measurement location on the product.

POM DATA IS AUTHORITATIVE.

NEVER derive numerical values by visually measuring the rendered image.

NEVER:

- estimate
- round
- interpolate
- invent
- normalize
- substitute measurements
- invent tolerances

POM COMPLETENESS:

Every supplied measurement/POM must appear.

Each POM must appear exactly once unless the structured data explicitly
requires multiple measurement references.

POM INFORMATION:

For every POM show:

- POM ID
- POM NAME
- measurement location
- measurement path
- exact base-size value
- exact tolerance
- exact unit

MEASUREMENT TYPES:

Correctly represent the supplied method:

- point-to-point
- edge-to-edge
- seam-to-seam
- vertical
- horizontal
- diagonal
- circumference
- radius
- diameter
- curved measurement
- component-specific measurement

Do not simplify a specialized measurement method.

MEASUREMENT GEOMETRY:

Each measurement must clearly communicate:

START
  ↓
MEASUREMENT PATH
  ↓
END

Use:

- extension lines
- measurement lines
- clean arrowheads
- clear labels
- adequate spacing

Keep dimension lines outside the product silhouette where possible.

Do not allow:

- ambiguous endpoints
- crossing measurement lines
- labels touching geometry
- overlapping values
- unreadable callouts

BASE SIZE:

Clearly identify the base/reference size used for the displayed
measurement values.

Do not mix values from different sizes.

PRODUCT GEOMETRY:

Use the same technical product representation as the front/back flats.

TITLE:

DIMENSION DIAGRAM

SUBTITLE:

POM BREAKPOINTS ON THE PRODUCT
PROCEDURAL — FROM STRUCTURED DATA

QUALITY STANDARD:

A factory technician must be able to determine:

WHERE to measure
WHAT to measure
HOW to measure
WHAT value is required
WHAT tolerance is allowed
`.trim(),
  },

  /* ---------------------------------------------------------------------- */
  /* SIZE GRADING                                                           */
  /* ---------------------------------------------------------------------- */

  "va-sizechart": {
    headline:
      "ASSET: SIZE GRADING — TECHNICAL SPECIFICATION PROGRESSION",

    body: `
OBJECTIVE:

Create a professional technical SIZE GRADING specification showing
how each supplied measurement changes across the defined variants.

This is NOT a consumer size chart.

It is a manufacturing specification.

VARIANT SYSTEM:

Use ONLY the sizes/variants supplied in the structured data.

Examples may include:

XS / S / M / L / XL

36 / 38 / 40 / 42

SMALL / MEDIUM / LARGE

CUSTOM VARIANT NAMES

Never invent a missing size.

POM MATRIX:

Display:

- POM ID
- POM name
- values for every defined variant
- tolerance where supplied
- grade change where calculable

NUMERICAL ACCURACY:

Every displayed value must come directly from the structured data.

Never:

- estimate
- round
- interpolate missing variants
- visually approximate values

GRADE STEP:

Where two consecutive values exist:

NEXT VALUE - PREVIOUS VALUE

Display the calculated grade step only when both values are present
and the calculation is valid.

Do not invent a grade step across missing data.

VISUALIZATION:

Use a professional technical matrix.

Each row represents one POM.

Each column represents one variant.

Values must be aligned vertically for rapid factory inspection.

Optionally show a compact progression indicator beside each row.

If geometry overlays are used:

- preserve actual variant proportions
- use only defined grading changes
- do not uniformly scale the product unless explicitly defined

HIERARCHY:

VARIANT
→ POM
→ VALUE
→ TOLERANCE
→ GRADE CHANGE

STYLE:

- technical data visualization
- precise rules
- generous whitespace
- restrained accent colour
- strong numeric alignment
- high legibility
- no decorative infographic illustrations

TITLE:

VARIANTS

SUBTITLE:

SIZE GRADING PROGRESSION
PROCEDURAL — FROM STRUCTURED DATA

The result should look like a professional factory specification sheet.
`.trim(),
  },

  /* ---------------------------------------------------------------------- */
  /* CARE                                                                   */
  /* ---------------------------------------------------------------------- */

  "va-care": {
    headline:
      "ASSET: CARE & COMPLIANCE — PRINT-READY LABEL STRIP",

    body: `
OBJECTIVE:

Create a production-quality care/compliance label graphic from
the supplied care and compliance data.

SYMBOL STANDARD:

Use the exact symbol standard specified by the structured data.

If ISO 3758 is explicitly specified, use the appropriate ISO 3758
care-symbol system.

Do not automatically assume ISO 3758 for non-apparel products.

Do not invent regulatory symbols.

Do not invent certification marks.

CARE SEQUENCE:

Preserve the exact order defined in the data.

Only include care categories actually supplied.

Possible categories include:

- washing
- bleaching
- drying
- tumble drying
- ironing
- professional cleaning
- drying method
- temperature limits
- warnings

TEXT:

Where supplied, display:

- product name
- fibre/material composition
- care instructions
- warnings
- compliance information

Preserve exact structured-data wording.

Do not normalize or rewrite composition.

Do not invent abbreviations.

SYMBOL STYLE:

- crisp vector-like appearance
- consistent dimensions
- aligned baseline
- equal spacing
- strong contrast
- print-safe geometry
- no gradients
- no shadows
- no 3D rendering

LAYOUT:

Create a horizontal production-ready label strip.

Allow sufficient spacing for real-world physical reproduction.

Do not overcrowd symbols.

TITLE:

CARE LABEL SYMBOLS

SUBTITLE:

COMPLIANCE DIAGRAM
PROCEDURAL — FROM STRUCTURED DATA
`.trim(),
  },

  /* ---------------------------------------------------------------------- */
  /* MATERIALS                                                              */
  /* ---------------------------------------------------------------------- */

  "va-materials": {
    headline:
      "ASSET: MATERIAL / COLOUR / TRIM BOARD",

    body: `
OBJECTIVE:

Create a professional material board documenting the actual materials,
colours, trims, hardware, and finishes defined in the structured data.

MATERIAL SOURCE:

The structured MATERIAL / BOM information is authoritative.

Create exactly one tile for each supplied material record.

Do not:

- duplicate materials
- merge materials
- invent materials
- invent suppliers
- invent compositions
- invent GSM
- invent material codes

MATERIAL TILE:

Where available, display:

MATERIAL ID
MATERIAL NAME
CATEGORY
COMPOSITION
GSM
WEIGHT
THICKNESS
COLOUR
COLOUR CODE
FINISH
SUPPLIER
SUPPLIER CODE

Only display fields that actually exist.

SWATCH REPRESENTATION:

Choose the appropriate visual representation based on the actual material.

TEXTILE:
Realistic macro weave or knit structure.

LEATHER:
Realistic grain and finish.

METAL:
Realistic machining, coating, plating, or surface finish.

PLASTIC:
Realistic surface, opacity, gloss, and finish.

WOOD:
Realistic grain and finish.

GLASS:
Realistic transparency and surface treatment.

RUBBER / SILICONE:
Appropriate matte/gloss technical surface.

PAPER / BOARD:
Appropriate fibre and board texture.

HARDWARE:
Technical representation of the actual supplied hardware.

The swatch must communicate MATERIAL IDENTITY.

Do not make the material more luxurious than it actually is.

COLOUR:

When exact colour information exists:

- preserve exact colour name
- preserve exact HEX
- preserve exact colour code
- preserve supplied Pantone where available

Do not artistically alter colour.

Do not use gradients for colour chips.

COLOUR CHIP SECTION:

Create a dedicated colour section containing:

COLOUR NAME
COLOUR CODE / HEX

Use the exact supplied values.

GRID ORGANIZATION:

Where applicable, organize materials into:

PRIMARY MATERIALS
SECONDARY MATERIALS
TRIMS
HARDWARE
LABELS
PACKAGING
OTHER COMPONENTS

Only render categories that actually exist.

TEXT ACCURACY:

All structured-data material text must be reproduced exactly.

TITLE:

MATERIAL SWATCHES

SUBTITLE:

MATERIAL & COLOUR BOARD
PROCEDURAL — FROM STRUCTURED DATA
`.trim(),
  },
};

/* -------------------------------------------------------------------------- */
/* FINAL VALIDATION                                                           */
/* -------------------------------------------------------------------------- */

/**
 * This block is intentionally appended after the asset-specific instructions.
 *
 * The model should receive the validation criteria immediately before the
 * structured data so the final context it sees is precision-oriented.
 */
const FINAL_VALIDATION = `
# FINAL PRE-RENDER VALIDATION

Before rendering, internally verify the following:

PRODUCT
[ ] Correct product identity.
[ ] Silhouette matches the reference.
[ ] Proportions remain consistent.
[ ] No product redesign.

GEOMETRY
[ ] No component invented.
[ ] No component removed without evidence.
[ ] No impossible geometry.
[ ] No accidental symmetry.
[ ] No accidental perspective where orthographic projection is required.

DATA
[ ] Every required structured value is preserved.
[ ] No dimension was invented.
[ ] No tolerance was invented.
[ ] No material was invented.
[ ] No colour was invented.
[ ] No variant was invented.
[ ] No construction operation was invented.
[ ] No compliance symbol was invented.

TEXT
[ ] Identifiers are accurate.
[ ] Numbers are accurate.
[ ] Units are accurate.
[ ] Names are accurate.
[ ] No hallucinated labels.
[ ] No paraphrased exact technical strings.

CONSISTENCY
[ ] Asset belongs to the same product system as all other assets.
[ ] Geometry is consistent with the technical flats.
[ ] Materials correspond to the material data.
[ ] Measurements correspond to the POM data.
[ ] Variants correspond to the defined size system.

PRIORITY:

TRUTH > PRECISION > CONSISTENCY > COMPLETENESS > DECORATION

If information is uncertain:

OMIT IT.

Never fabricate information to make the artwork look complete.

Return ONLY the requested generated image.
`.trim();

/* -------------------------------------------------------------------------- */
/* PROMPT BUILDER                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Build the complete AI prompt for one visual asset.
 *
 * Structure:
 *
 *   1. Asset identity
 *   2. Asset-specific rendering instructions
 *   3. Global technical-documentation system
 *   4. Final validation
 *   5. Complete structured pack data
 *
 * Putting the data last gives the model the actual values immediately after
 * the precision/validation rules.
 */
export function buildVisualPrompt(
  assetId: string,
  ctx: VisualPromptContext,
): string {
  const directive =
    DIRECTIVES[assetId as VisualAssetId] ??
    DIRECTIVES["va-hero"];

  const structuredData = summarizePackData(
    ctx.pack,
    ctx.sizes,
  );

  return [
    directive.headline,

    directive.body,

    GLOBAL_VISUAL_SYSTEM,

    FINAL_VALIDATION,

    "# STRUCTURED PACK DATA",
    "The following is the factual product specification.",
    "Use it as the authoritative source for every value rendered.",
    "Do not invent missing information.",
    "",
    structuredData,
  ].join("\n\n");
}
